language: go
go:
- 1.7.4
install:
- go get ./...
- go get -t ./...
script:
  - go test -v ./...
notifications:
  email:
  - zmap-devel@umich.edu
  slack:
    secure: C9nvJpSXSBuqfyv7z+vt+d0CQ4ZC5JklQj9iY9g1jpObDeBG13/THKxINTAAkKIjrgZHkeSVRjOSAE+pz6XbGKFBoFwsKqx9kc4rM7rZumlRalXgyTMc2nInWVcCwlQBGHTAmqPudXR4zMD8xRM9iNxpzOIb2cjOkPRAHw1cCXY=
